# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ BricksSiteBundle, BricksUserBundle ]
    java:           %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp: ~
    assets:
        lesses:
            inputs:
                - %kernel.root_dir%/../web/assets/bootstrap/less/bootstrap.less
                - @BricksSiteBundle/Resources/less/*.less
                - @BricksWikiBundle/Resources/less/*.less
                - @BricksUserBundle/Resources/less/*.less
                - @BricksMessageBundle/Resources/less/*.less
            filters: lessphp
        stylesheets:
            inputs:
                - %kernel.root_dir%/../web/assets/rainbow/themes/github.css

                - @lesses
                - %kernel.root_dir%/../web/assets/FortAwesome-Font-Awesome-3.0/css/font-awesome.min.css
            filters:
                - cssrewrite
                - ?yui_css
        javascripts_header:
            inputs:
                - %kernel.root_dir%/../web/assets/jquery/jquery-1.8.2.js
                - bundles/fosjsrouting/js/router.js
            filters:
                - cssrewrite
                - ?yui_css
        javascripts_footer:
            inputs:
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap.min.js
                - %kernel.root_dir%/../web/assets/bootstrap-tags/lib/bootstrap-tags.js
                - %kernel.root_dir%/../web/assets/socialite/socialite.js

                #https://github.com/ccampbell/rainbow
                - %kernel.root_dir%/../web/assets/rainbow/js/rainbow.min.js
                - %kernel.root_dir%/../web/assets/rainbow/js/language/generic.js
                - %kernel.root_dir%/../web/assets/rainbow/js/language/php.js
                - %kernel.root_dir%/../web/assets/rainbow/js/language/html.js
                - %kernel.root_dir%/../web/assets/rainbow/js/language/javascript.js
                # https://github.com/Blender3D/rainbow.linenumbers.js
                - %kernel.root_dir%/../web/assets/rainbow.linenumbers.js-master/rainbow.linecount.js

                - @BricksSiteBundle/Resources/js/*.js
                - @BricksSiteBundle/Resources/js/*/*.js
                - @BricksMessageBundle/Resources/js/*.js
            filters:
                - cssrewrite
                - ?yui_css