####################################################################################################
# HWIOAuthBundle routes
####################################################################################################
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

# hwi_oauth
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

github_login:
    pattern: /login/github

github_check:
    pattern: /login/check-github

sensiolabs_connect_check:
    pattern: /login/check-sensiolabs-connect

logout:
    pattern: /logout

login_check:
    pattern: /login_check
#    pattern: /en/login_check
#    pattern:   /{_locale}/login_check
#    defaults:  { _locale: %locale% }
#    requirements:
#        _locale:  %route_locale_requirements%



####################################################################################################
# Bricks bundles routes
####################################################################################################

# homepage not localized: load the homepage with default language
index_not_localized:
    pattern:   /
    defaults:  { _controller: BricksSiteBundle:Default:index, _locale: %locale% }

# Bricks routes
bricks_site:
    resource: "@BricksSiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

bricks_wiki:
    resource: "@BricksWikiBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/wiki
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%
    
bricks_user:
    resource: "@BricksUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

bricks_message:
    resource: "@BricksMessageBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

# additional unlocalized login action
#login:
#    pattern:   /login
#    defaults:  { _controller: FOSUserBundle:Security:login, _locale: %locale% }

# required unlocalized logout action
#logout:
#    pattern:   /logout
#    defaults:  { _controller: FOSUserBundle:Security:logout, _locale: %locale% }

####################################################################################################
# FOSJsRoutingBundle routes
####################################################################################################
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"        

####################################################################################################
# FOSUserBundle routes
####################################################################################################
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    prefix:   /{_locale}/
#    defaults:  { _locale: %locale% }
#    requirements:
#        _locale:  %route_locale_requirements%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /{_locale}/register
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%

####################################################################################################
# FOSMessageBundle
####################################################################################################
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /{_locale}/user/message
    defaults:  { _locale: %locale% }
    requirements:
        _locale:  %route_locale_requirements%
